config/routes.rb
require "sidekiq/pro/web"
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"

  root "coins#index"

  post 'login', to: "users#login", as: :login
  post 'logout', to: "users#logout", as: :logout
  get 'users/coins', to: "users#coins", as: :user_coins

  resources :coins, only: [:index, :show] do
    post :add_comment, on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coin.rb
class Coin < ApplicationRecord
  has_many :user_coins
  has_many :users, through: :user_coins
  has_many :user_comments

  def rating
    user_comments.average(:rating)
  end

  def chain
    case chain_id
    when 1
      "ETH"
    when 137
      "MATIC"
    else
      ""
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_coins
  has_many :coins, through: :user_coins

  def is_hold?(coin_id)
    user_coins.exists?(coin_id: coin_id)
  end
end

app/models/user_coin.rb
class UserCoin < ApplicationRecord
  belongs_to :user
  belongs_to :coin
end

app/models/user_comment.rb
class UserComment < ApplicationRecord
  belongs_to :user
  belongs_to :coin
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  before_action :get_coin, except: :index

  def index
    @records = Coin.includes(:user_coins, :users).where(user_coins: {is_hold: true}).sort_by{|c| c.users.count}.reverse
  end

  def show
    @comments = @coin.user_comments.order(created_at: :desc).page(params[:page]).per(10)
  end

  def add_comment
    @coin.user_comments.create(body: params[:comment], user_id: current_user.id, rating: params[:rating])

    redirect_to coin_path(@coin), notice: 'Comment added'
  end

  private
  def get_coin
    @coin = Coin.find params[:id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def login
    user = User.where(address: params[:address]).first_or_create
    session[:user_id] = user.id
    SyncUserCoinsJob.perform_later(user.address)

    redirect_to user_coins_path, notice: "Sync data successfully, please reload page after 5 minutes"
  end

  def logout
    session[:user_id] = nil if session[:user_id]

    render json: {success: true}
  end

  def coins
    @records = current_user.coins.includes(:user_coins, :users).where(user_coins: {is_hold: true}).sort_by{|c| c.users.count}.reverse
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def date_format(datetime)
    datetime.strftime('%Y-%m-%d')
  end

  def address_format(address)
    address[-8..-1]
  end

  def decimal_format(data)
    data.to_f.round(3)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/coins/_records.html.erb
<% @comments.each do |comment| %>
  <div class="d-flex align-items-start">
    <div class="flex-grow-1">
      <small class="float-end"><%= "#{time_ago_in_words comment.created_at} ago" %></small>
      <strong><%= address_format comment.user.address %></strong><span class="ms-3 review-rating" data-score="<%= comment.rating %>"></span>
      <br />
      <p class="mt-3"><%= comment.body %></p>
    </div>
  </div>
  <hr />
<% end %>

app/views/coins/index.html.erb
<div class="mb-5 mx-5 row">
  <% @records.each do |record| %>
    <div class="col-6">
      <div class="card" style="height:310px;">
        <div class="card-header">
          <h5 class="card-title mb-0">
            <img src="<%= record.logo %>" class="rounded-circle" width="50" onerror="this.onerror=null;this.src='<%= asset_url("placeholder.png") %>'" />
            <span><%= link_to record.symbol, coin_path(record), class: "h3" %></span>
            <span class="h4 float-end mt-2">
              Chain: <span class="ms-2 float-end"><%= record.chain %></span>
              <br />
              Holders: <span class="float-end"><%= record.users.count %></span>
            </span>
          </h5>
        </div>
        <div class="card-body">
          <% record.user_comments.each do |comment| %>
            <p class="card-text">
              <p>
                <%= truncate(comment.body) %>
                <small class="float-end"><%= "#{time_ago_in_words comment.created_at} ago" %></small>
              </p>
            </p>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/coins/show.html.erb
<div class="row ms-5">
  <div class="col-8 mx-auto">
    <div class="card mb-3 text-center">
      <div class="card-body">
        <h1 class="h3 mb-3"><%= @coin.symbol %></h1>
      </div>
      <hr class="my-0" />
      <div class="text-center"><img src="<%= @coin.logo %>" class="rounded-circle" width="200px" onerror="this.onerror=null;this.src='<%= asset_url("placeholder.png") %>'" /></div>
      <div class="card-body">
        <h3>
          Rating:
          <span class="review-rating" data-score="<%= @coin.rating.to_i %>"></span>
        </h3>
      </div>
    </div>
    <div>
      <div class="card">
        <div class="card-header">
          <h3 class="mb-0">Comments</h3>
        </div>
        <div class="card-body h-100">
          <div id="comments">
            <%= render "records" %>
          </div>
          <div class="p-4">
            <%= link_to "More", "#", class: "btn btn-primary btn-block loadMoreBtn", remote: true %>
          </div>
          <% if current_user.is_hold?(@coin.id) %>
            <%= form_tag add_comment_coin_path(@coin.id) do %>
              <div class="form-group my-3">
                <div id="rating-form"><label class="me-3">Rating</label></div>
                <textarea class="form-control mt-3" id="comment" name="comment" rows="3"></textarea>
              </div>
              <button type="submit" class="btn btn-primary">Add comment</button>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<%= hidden_field_tag :current_page, @comments.current_page %>

app/views/coins/show.js.erb
$("#comments").append("<%= j render partial:'records' %>");
$("#current_page").val("<%= params[:page].to_i %>");

app/views/home/index.html.erb
<div class="text-center">
  <div class="welcome-intro">
    <h1>Keep up with all the important happenings in the web3world</h1>
    <%= button_tag "Connect MetaMask", class: "btn btn-warning metamask_login" unless current_user %>
  </div>
</div>

app/views/layouts/_notices.html.erb
<% type_mapping = { alert: :danger, notice: :success } %>
<% flash.each do |k, v| %>
  <% k = type_mapping[k.to_sym] if type_mapping[k.to_sym].present?  %>
  <div class="alert alert-<%= k %> alert-dismissible fade show mt-2" role="alert">
    <strong><%= sanitize(v.to_s) %></strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Coin Dig</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body data-theme="dark">
    <div class="wrapper">
      <div class="main">
        <nav class="navbar navbar-expand navbar-light navbar-bg">
          <h3>Coin Dig</h3>
          <div class="sidebar-item">
            <%= link_to "Home", root_path, class: "sidebar-link" %>
          </div>
          <div class="navbar-collapse collapse">
            <ul class="navbar-nav navbar-align">
              <li class="nav-item dropdown">
                <div class="align-items-center loginBtns">
                  <div class="navbar-tool dropdown connect-btn">
                    <%= link_to "Connect Metamask", "#", class: "btn btn-warning", id: "loginBtn" %>
                  </div>
                  <div class="navbar-tool dropdown hide">
                    <a href="#" role="button" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                      <h4 id="login_address" class="d-inline-block"></h4>
                    </a>
                    <div class="dropdown-menu dropdown-menu-end">
                      <%= link_to user_coins_path, class: "dropdown-item" do %>
                        <i class="ai-log-out fs-base me-2"></i>
                        <span>My coins</span>
                      <% end %>
                      <%= link_to "#", class: "dropdown-item", id: "logoutBtn" do %>
                        <i class="ai-log-out fs-base me-2"></i>
                        <span>Sign out</span>
                      <% end %>
                    </div>
                  </div>
                </div>
              </li>
            </ul>
          </div>
        </nav>
        <main class="content">
          <%= render "layouts/notices" %>
          <%= yield %>
        </main>
        <footer class="footer">
          <div class="py-4 py-md-3">
            <div class="container d-md-flex align-items-center justify-content-center pt-3">
                <p class="fs-sm pt-2 mb-3"><span class="text-black opacity-50 me-1">© All rights reserved. Made by Coinbay Networks, Inc</span></p>
              </div>
            </div>
          </div>
        </footer>
      </div>
    </div>
    <div id="spinner" class="hide">
      <%= image_tag("loading.svg") %>
    </div>
  </body>
</html>

app/views/users/coins.html.erb
<div class="mb-5 mx-5">
  <h3>My Coins</h3>
  <table class="table">
    <thead>
      <th>Coin</th>
      <th>Chain</th>
    </thead>
    <tbody>
      <% @records.each do |record| %>
        <tr>
         <td>
           <img src="<%= record.logo %>" class="rounded-circle" width="20" onerror="this.onerror=null;this.src='<%= asset_url("placeholder.png") %>'" />
            <%= link_to record.symbol, coin_path(record) %>
         </td>
         <td><%= record.chain %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>